PATHS:
  FRAMES_TABLE: 'B:/Datasets/view_classifier/internal_1/frames.csv'
  FRAMES_DIR: 'B:/Datasets/view_classifier/internal_1/frames'
  CLIPS_TABLE: 'B:/Datasets/view_classifier/internal_1/clips_by_patient_hackathon.csv'
  PARTITIONS_DIR: 'B:/Datasets/view_classifier/internal_1/partitions'
  HEATMAPS: 'img/heatmaps'
  LOGS: 'results/logs/'
  IMAGES: 'results/figures/'
  MODEL_WEIGHTS: 'results/models/'
  MODEL_TO_LOAD: 'results/models/example_model.h5'
  CLASS_NAME_MAP: 'data/serializations/class_name_map.pkl'
  BATCH_PREDS: 'results/predictions/'
  METRICS: './results/metrics/'
  EXPERIMENTS: './results/experiments/'

DATA:
  IMG_DIM: [128, 128]
  VAL_SPLIT: 0.1
  TEST_SPLIT: 0.1
  CLASSES: ['parenchymal', 'pleural']   # Classes for binary classification

TRAIN:
  MODEL_DEF: 'mobilenetv2'
  N_CLASSES: 2
  BATCH_SIZE: 256
  EPOCHS: 10
  PATIENCE: 8
  EXPERIMENT_TYPE: 'single_train'   # One of {'single_train'}
  DATA_AUG:
    ZOOM_RANGE: 0.2
    HORIZONTAL_FLIP: true
    WIDTH_SHIFT_RANGE: 0.2
    HEIGHT_SHIFT_RANGE: 0.2
    SHEAR_RANGE: 10
    ROTATION_RANGE: 0.125   # Fraction of 2*pi
    BRIGHTNESS_RANGE: 0.2
    CONTRAST_RANGE: 0.1
  HPARAM_SEARCH:
    N_EVALS: 10
    HPARAM_OBJECTIVE: 'auc'

HPARAMS:
  MOBILENETV2:
    LR: 0.0001
    DROPOUT: 0.4
    L2_LAMBDA: 0.0001
    NODES_FC0: 32
    FROZEN_LAYERS: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36]

CLIP_PREDICTION:
  CLASSIFICATION_THRESHOLD: 0.5

HPARAM_SEARCH:
  MODEL1:
    LR:
      TYPE: 'float_log'
      RANGE: [0.00001, 0.001]
    DROPOUT:
      TYPE: 'float_uniform'
      RANGE: [0.0, 0.5]
  MODEL2:
    LR:
      TYPE: 'float_log'
      RANGE: [ 0.00001, 0.001 ]
    DROPOUT:
      TYPE: 'float_uniform'
      RANGE: [0.0, 0.5]