PATHS:
  FRAMES_TABLE: 'C:\Users\Bennet\DeepBreathe\data\masked_clips\frames.csv'
  FRAMES_DIR: 'C:\Users\Bennet\DeepBreathe\data\masked_clips\frames'
  CLIPS_TABLE: 'C:\Users\Bennet\DeepBreathe\data\masked_clips\clips_table.csv'
  PARTITIONS_DIR: 'C:\Users\Bennet\DeepBreathe\data\masked_clips\partitions'
  MASKED_CLIPS_DIR: 'C:\Users\Bennet\DeepBreathe\data\masked_clips'
  TEST_FRAMES_TABLE: 'C:\Users\Bennet\DeepBreathe\data\masked_clips\partitions\20211125-224334\test_set_frames.csv'
  TEST_CLIPS_TABLE: 'C:\Users\Bennet\DeepBreathe\data\masked_clips\partitions\20211125-224334\test_set_clips.csv'
  FRAME_PREDICTIONS: 'results/predictions/frame_predictions20211126-181026.csv'
  MODEL_TO_LOAD: 'results/models/model20211125-224334-cutoffvgg16.h5'
  HEATMAPS: 'img/heatmaps'
  LOGS: 'results/logs/'
  IMAGES: 'results/figures/'
  MODEL_WEIGHTS: 'results/models/'
  BATCH_PREDS: 'results/predictions/'
  METRICS: './results/metrics/'
  EXPERIMENTS: './results/experiments/'
  EXPERIMENT_IMG: './img/experiments/'

DATA:
  IMG_DIM: [128, 128]
  VAL_SPLIT: 0.1
  TEST_SPLIT: 0.1
  CLASSES: ['parenchymal', 'pleural']   # Classes for binary classification

TRAIN:
  MODEL_DEF: 'vgg16'
  N_CLASSES: 2
  BATCH_SIZE: 128
  EPOCHS: 10
  PATIENCE: 8
  EXPERIMENT_TYPE: 'single_train'   # One of {'single_train'}
  DATA_AUG:
    ZOOM_RANGE: 0.2
    HORIZONTAL_FLIP: true
    WIDTH_SHIFT_RANGE: 0.2
    HEIGHT_SHIFT_RANGE: 0.2
    SHEAR_RANGE: 10
    ROTATION_RANGE: 0.125   # Fraction of 2*pi
    BRIGHTNESS_RANGE: 0.2
    CONTRAST_RANGE: 0.1
  HPARAM_SEARCH:
    N_EVALS: 10
    HPARAM_OBJECTIVE: 'auc'

HPARAMS:
  MOBILENETV2:
    LR: 0.0001
    DROPOUT: 0.4
    L2_LAMBDA: 0.0001
    NODES_FC0: 32
    FROZEN_LAYERS: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,16,17,18,19,20,21,22,23,24,25,26,26,27,28,29,30]
  INCEPTIONV3:
    LR: 0.0001
    DROPOUT: 0.4
    L2_LAMBDA: 0.0001
    NODES_FC0: 32
    FROZEN_LAYERS: [ 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]
  RESNET50V2:
    LR: 0.0001
    DROPOUT: 0.4
    L2_LAMBDA: 0.0001
    NODES_FC0: 32
    FROZEN_LAYERS: [ 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36]
  VGG16:
    LR: 0.01
    DROPOUT: 0.5
    L2_LAMBDA: 0.01
    NODES_DENSE0: 64
    FROZEN_LAYERS: []
  CUTOFFVGG16:
    LR_EXTRACT: 0.0003
    LR_FINETUNE: 0.0000093
    DROPOUT: 0.45
    CUTOFF_LAYER: 10
    FINETUNE_LAYER: 7
    EXTRACT_EPOCHS: 5

CLIP_PREDICTION:
  CLASSIFICATION_THRESHOLD: 0.5
  CLIP_PREDICTION_METHOD: 'contiguity_threshold'   # one of {'majority_vote', 'average', 'max_sliding_window', 'contiguity_threshsold'}
  WINDOW_SIZE: 20
  CONTIGUITY_THRESHOLD: 20

HPARAM_SEARCH:
  MODEL1:
    LR:
      TYPE: 'float_log'
      RANGE: [0.00001, 0.001]
    DROPOUT:
      TYPE: 'float_uniform'
      RANGE: [0.0, 0.5]
  MODEL2:
    LR:
      TYPE: 'float_log'
      RANGE: [ 0.00001, 0.001 ]
    DROPOUT:
      TYPE: 'float_uniform'
      RANGE: [0.0, 0.5]